### ISSUE TITLE
Extracted classifier in a separated repo

### ISSUE THREAD

**Issue by arnauorriols** [douban/linguist#15]
Hi,

I was in a need to use the classifier to calculate the probability of a programming language for a given code snippet. As I was having trouble installing pygments and some other dependencies I didn't care about, and thought that there is enough separation of concerns between both tools, I've extracted the classifier and other related modules [to a separated repository](https://github.com/arnauorriols/plangclassifier)

I would be happy if you would consider extracting it to a repository of yours, please let me know if you do, and I will delete mine.

**Comment by xtao** [comment]
@arnauorriols Sorry for the late reply. We do not have any separated repo plan, you can keep your repo as you wish.
